# Generated by Django 5.1.7 on 2025-04-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Título', models.CharField(max_length=64)),
                ('descrição', models.CharField(max_length=1000)),
                ('lance_inicial', models.FloatField()),
                ('imagem', models.URLField()),
                ('categoria', models.CharField(max_length=64)),
            ],
        ),
    ]
