# Generated by Django 5.1.7 on 2025-04-15 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_anuncio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('sobrenome', models.CharField(max_length=64)),
                ('lance', models.FloatField()),
                ('comentario', models.CharField(max_length=1000)),
                ('tituloescolhido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tituloescolhido', to='auctions.anuncio')),
            ],
        ),
    ]
