# Generated by Django 5.1.7 on 2025-04-15 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_lance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='Título',
            new_name='titulo',
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('data', models.DateField()),
                ('comentario', models.CharField(max_length=1000)),
                ('tituloacomentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tituloacomentar', to='auctions.anuncio')),
            ],
        ),
    ]
