# Generated by Django 5.1.7 on 2025-04-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_título_anuncio_titulo_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
